name: ColdTracker
version: '@version@'
main: dev.padrewin.coldtracker.ColdTracker
api-version: '1.20'
authors: [ padrewin ]
depend: [LuckPerms]

commands:
  coldtracker:
    permission: "coldtracker.version"
  reload:
    permission: "coldtracker.reload"
  showtime:
    permission: "coldtracker.showtime"
  wipe:
    permission: "coldtracker.wipe"
  dump:
    permission: "coldtracker.dump"

permissions:
  coldtracker.*:
    description: Root command for ColdTracker plugin
    children:
      coldtracker.version: true
      coldtracker.showtime: true
      coldtracker.reload: true
      coldtracker.wipe: true
      coldtracker.dump: true
      coldtracker.export: true

  coldtracker.version:
    description: Gives access to the version command
    default: true

  coldtracker.showtime:
    description: Gives access to the showtime command
    default: op

  coldtracker.reload:
    description: Gives access to the reload command
    default: op

  coldtracker.wipe:
    description: Gives access to the wipe command
    default: op

  coldtracker.dump:
    description: Gives access to the dump command
    default: op

  coldtracker.tracktime:
    description: Gives access to track the time
    default: op

  coldtracker.export:
    description: Gives access to the export command
    default: op